"""KVCache upper bound oracle package."""

from .core import EffectiveRequest, MachineProfile, ModelProfile, RequestRecord, Scope
from .ingest import (
    NormalizationResult,
    NormalizationStats,
    TraceLoadResult,
    TraceLoadStats,
    build_effective_requests,
    load_request_records,
    window_to_block_count,
)
from .oracle import (
    CapacityAnalysisResult,
    CapacityRequestMetric,
    CapacitySummary,
    ContentAnalysisResult,
    ContentRequestMetric,
    ContentSummary,
    PrefixTrie,
    PrefixTrieNode,
    analyze_capacity_upper_bound,
    analyze_content_upper_bound,
)
from .reporting import (
    BucketAnalysisConfig,
    BucketAnalysisResult,
    BucketCapacityTier,
    BucketDeploymentConfig,
    BucketReportRow,
    analyze_bucket_deployments,
    load_bucket_analysis_config,
    write_bucket_outputs,
)

__all__ = [
    "BucketAnalysisConfig",
    "BucketAnalysisResult",
    "BucketCapacityTier",
    "BucketDeploymentConfig",
    "BucketReportRow",
    "CapacityAnalysisResult",
    "CapacityRequestMetric",
    "CapacitySummary",
    "ContentAnalysisResult",
    "ContentRequestMetric",
    "ContentSummary",
    "EffectiveRequest",
    "MachineProfile",
    "ModelProfile",
    "NormalizationResult",
    "NormalizationStats",
    "PrefixTrie",
    "PrefixTrieNode",
    "RequestRecord",
    "Scope",
    "TraceLoadResult",
    "TraceLoadStats",
    "analyze_bucket_deployments",
    "analyze_capacity_upper_bound",
    "analyze_content_upper_bound",
    "build_effective_requests",
    "load_request_records",
    "load_bucket_analysis_config",
    "window_to_block_count",
    "write_bucket_outputs",
]
